### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [arpa2/tlspool#136]
Dear @arpa2 team,

Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Channel Bindings for TLS: https://datatracker.ietf.org/doc/html/rfc5929

- XEP-0388: Extensible SASL Profile: https://xmpp.org/extensions/xep-0388.html
- XEP-0440: SASL Channel-Binding Type Capability: https://xmpp.org/extensions/xep-0440.html
- XEP-0474: SASL SCRAM Downgrade Protection: https://xmpp.org/extensions/xep-0474.html
- XEP-0480: SASL Upgrade Tasks: https://xmpp.org/extensions/xep-0480.html

Little details, to know easily:
- tls-unique for TLS =< 1.2 (RFC5929)
- tls-server-end-point =< 1.2 + 1.3 (RFC5929)
- tls-exporter for TLS = 1.3 (RFC9266)

After the jabber.ru MITM, it is time to add it:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch/certwatch

Thanks in advance.

Linked to:
- Channel Binding: https://github.com/scram-sasl/info/issues/1
- https://github.com/arpa2/tlspool/issues/69
- https://github.com/arpa2/tlspool/commit/7b5afe099bf16f505caf956ed90c59fb04700218
- https://github.com/arpa2/tlspool-windows/commit/7b5afe099bf16f505caf956ed90c59fb04700218

**Comment by vanrein** [comment]
This repository has been reduced to a [redirection](https://gitlab.com/arpa2/tlspool).  Please file an issue in the new location, so the conversation starts with you on board.

The request is a good idea, thanks for adding it.  I will look into it when I can (finally) move my focus back on finishing the TLS Pool.  If you are in a hurry I could consider a merge request at GitLab much faster.
