### ISSUE TITLE
TLSPOOL_CFGFILE vs. TLSPOOL_CONFIGFILE

### ISSUE THREAD

**Issue by qknight** [arpa2/tlspool#53]
documentation is wrong, because it should be `TLSPOOL_CFGFILE` instead of `TLSPOOL_CONFIGFILE`

https://github.com/arpa2/tlspool/blob/master/lib/libtlspool_configvar.c#L22
https://github.com/arpa2/tlspool/blob/master/lib/libtlspool_configvar.c#L40

**Comment by vanrein** [comment]
Resolved in 77cc246dbb048226706176d36876a91434260e6d

I changed both to `TLSPOOL_CONFIG_FILE` which is more in line with other variables.  Thanks for reporting.
