### ISSUE TITLE
Channel binding support

### ISSUE THREAD

**Issue by vanrein** [arpa2/tlspool#69]
Allow for the extraction of

 1. hashed TLS server certificate
 2. one-but-last Finished message

for the use with [channel binding for TLS](https://www.iana.org/assignments/channel-binding-types/channel-binding-types.xhtml) in SASL and GSS-API mechanisms.  Details are in [RFC 5929](
http://www.iana.org/go/rfc5929).

**Comment by vanrein** [comment]
Defined quite a variety of info kinds, not just for channel binding.  Most fields will return `E_TLSPOOL_INFO_NOT_FOUND`, "TLS Pool cannot answer the info query" -- this is something to work out later, when called for.

**Comment by vanrein** [comment]
Will be resolved together with #100, support for name checking.

**Comment by vanrein** [comment]
resolved in 7b5afe099bf16f505caf956ed90c59fb04700218 and its parent 61182484b7a0d463bb22d4b015690a97e5961ae0

from the commit message:

    Implemented the most important variant, tls-unique.
    GnuTLS does not support the other one in RFC 5929,
    namely tls-server-end-point, but we might infer that
    ourselves --  it is merely a certificate hash.  It
    is also less interesting as it cannot distinguish
    TLS sesssions, so we will sit and wait if this is
    indeed required by anyone.  This closes issue #69.
    
    Two test runs report the same information on both
    ends, but different among sessions.  With the
    tls-server-end-point, the two test runs would yield
    the same outcome.  This is why we are not keen on
    carrying the weaker form.
    
    1.
    tlspool-test-client: Channel binding info, tls-unique, 12 bytes of 12: 1c 47 7f 50 84 e5 85 c3 50 24 71 06
    tlspool-test-server: Channel binding info, tls-unique, 12 bytes of 12: 1c 47 7f 50 84 e5 85 c3 50 24 71 06
    
    2.
    tlspool-test-client: Channel binding info, tls-unique, 12 bytes of 12: 18 49 6d a4 b8 c3 fc db 14 9a ba 4b
    tlspool-test-server: Channel binding info, tls-unique, 12 bytes of 12: 18 49 6d a4 b8 c3 fc db 14 9a ba 4b

**Comment by Neustradamus** [comment]
@vanrein: I search help maybe you can?

Qt QSslSocket:
- https://bugreports.qt.io/browse/QTBUG-77783

QCA:
- https://bugs.kde.org/show_bug.cgi?id=411184

NSS:
- https://bugzilla.mozilla.org/show_bug.cgi?id=563276

...

**Comment by vanrein** [comment]
Hi Neustradamus,

> @vanrein: I search help maybe you can?

Let's see what I can do.  You're not considering to use the TLS Pool itself, I think to read here, so you'll have to figure out how to do it the OpenSSL way.

Channel binding is meant to provide information that can be cryptographically hashed into the SASL authentication system.  You can get it by looking at the right place in the traffic flow.

Of the two defined forms, "tls-server-end-point" works with the server cert, so it distinguishes servers but not connections.  The latter is what "tls-unique" does, by providing random information.

The code that the TLS Pool uses for this is found here,

https://github.com/arpa2/tlspool/blob/b2eb1dd6bd30851f4a5f41195eda185cc469d631/src/gnutls.c#L5818-L5849

It's pretty simple, really, just exporting data from, in our case, GnuTLS to the client environment.

Although the TLS Pool exports identity information but conceals the form (X.509 cert, PGP key, Kerberos ticket, ...) this should be pretty much what you need too -- just export the literal bytes that are needed by SASL.


Please close the ticket when this is answered, or continue asking.

-Rick

**Comment by vanrein** [comment]
Oh,

> [...] so it distinguishes servers but not connections.  The latter is what "tls-unique" does, by providing random information.

Not random information but a recent Finished message.

I am not sure if/how this changes under TLS 1.3, where the server sends its Finished message quite a bit earlier than under TLS 1.2 and, most importantly, before the client instead of after it.  Please use API routines to avoid trouble of that kind (you don't want to code TLS version specifics in your application, I'm sure).

-Rick

**Comment by Neustradamus** [comment]
@vanrein: It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Linked to:
- https://github.com/arpa2/tlspool/issues/136
