### ISSUE TITLE
Suspected memory leak on Windows

### ISSUE THREAD

**Issue by vanrein** [arpa2/tlspool#77]
It looks like this code,
https://github.com/arpa2/tlspool/blob/4ee29f57b52966d9673f92e309c6a265aaf5fee1/src/service.c#L508-L558
does not free the message while it is being sent.  The other code sets `cmd->claimed=0` to allow recollection of the `cmd` structure.  Is this indeed a memory leak?

If so, please hold.  A new version is coming up which distinguishes the two cases.  This is how this was discovered in the first place.

**Comment by hfmanson** [comment]
Yep, cmd->claimed=0 should be applied too in the windows version of send_command

**Comment by vanrein** [comment]
Has this been fixed?  Then please close the issue.

**Comment by vanrein** [comment]
Seems resolved in the upcoming Windows release.
